export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_ERROR = "GET_ALL_USER_ERROR";


export const GET_SEARCH_USER_REQUEST = "GET_SEARCH_USER_REQUEST";
export const GET_SEARCH_USER_SUCCESS = "GET_SEARCH_USER_SUCCESS";
export const GET_SEARCH_USER_ERROR = "GET_SEARCH_USER_ERROR";
